<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Soal3Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('soal')->insert([
            [
                'id_sesi' => 10,
                'tipe' => 'multiple',
                'soal' => 'Apa fungsi dari perintah INSERT dalam SQL?',
                'opsi' => json_encode(['Menambahkan', 'Mengurangi', 'Menghapus', 'Data', 'Lama', 'Baru']),
                'jawaban' => json_encode(['Menambahkan', 'Data', 'Baru']),
            ],
            [
                'id_sesi' => 10,
                'tipe' => 'text',
                'soal' => 'Tulis sintaks dasar perintah INSERT dalam SQL.',
                'opsi' => null,
                'jawaban' => json_encode(['INSERT', 'VALUES']),
            ],
            [
                'id_sesi' => 10,
                'tipe' => 'mcq',
                'soal' => 'Apakah benar kita bisa menghilangkan daftar kolom saat menggunakan INSERT?',
                'opsi' => json_encode(['Benar', 'Salah']),
                'jawaban' => json_encode(['Benar']),
            ],
            [
                'id_sesi' => 10,
                'tipe' => 'mcq',
                'soal' => 'Pilih perintah INSERT yang benar',
                'opsi' => json_encode(['SELECT', 'INTO', 'DROP', 'FROM']),
                'jawaban' => json_encode(['INTO']),
            ],
            [
                'id_sesi' => 10,
                'tipe' => 'mcq',
                'soal' => 'Apa yang harus diperhatikan saat memasukkan data INTEGER?',
                'opsi' => json_encode(['Angka', 'Huruf', 'Simbol', 'Kalimat']),
                'jawaban' => json_encode(['Angka']),
            ],
            [
                'id_sesi' => 10,
                'tipe' => 'mcq',
                'soal' => 'Manakah perintah INSERT yang benar untuk tabel "pegawai"',
                'opsi' => json_encode([
                    'INSERT INTO pegawai (……,…..,…..) VALUES (…..,…..,…..);',
                    'INSERT pegawai VALUES (…..,…..,…..);',
                    'INSERT INTO pegawai (…..,…..,…..) VALUE (…..,…..,…..);'
                ]),
                'jawaban' => json_encode(['INSERT INTO pegawai (……,…..,…..) VALUES (…..,…..,…..);']),
            ],
            [
                'id_sesi' => 10,
                'tipe' => 'mcq',
                'soal' => 'Bagaimana cara menambahkan produk baru ke tabel "produk"?',
                'opsi' => json_encode([
                    'INSERT INTO produk (…..,…..,…..) VALUES (…..,…..,…..);',
                    'INSERT produk (…..,…..,…..) VALUE (…..,…..,…..);',
                    'INSERT INTO produk (…..,…..,…..)'
                ]),
                'jawaban' => json_encode(['INSERT INTO produk (…..,…..,…..) VALUES (…..,…..,…..);']),
            ],
            [
                'id_sesi' => 10,
                'tipe' => 'mcq',
                'soal' => 'Apa yang terjadi jika kita memasukkan nilai yang tidak sesuai dengan tipe data kolom?',
                'opsi' => json_encode(['BERHASIL', 'LOADING', 'ERROR']),
                'jawaban' => json_encode(['ERROR']),
            ],
            [
                'id_sesi' => 10,
                'tipe' => 'multiple',
                'soal' => 'Bagaimana perintah INSERT jika kita hanya ingin memasukkan data ke beberapa kolom saja?',
                'opsi' => json_encode(['INTO', 'FROM', 'TO', 'DATA', 'VALUE', 'VALUES']),
                'jawaban' => json_encode(['INTO', 'VALUES']),
            ],
            [
                'id_sesi' => 10,
                'tipe' => 'mcq',
                'soal' => 'Mana perintah INSERT yang benar untuk tabel "pelanggan" tanpa menyebutkan kolom?',
                'opsi' => json_encode([
                    'INSERT INTO pelanggan VALUES (…..,…..,…..);',
                    'INSERT pelanggan VALUES (…..,…..,…..);',
                    'INSERT INTO pelanggan (…..,…..,…..) (…..,…..,…..);'
                ]),
                'jawaban' => json_encode(['INSERT INTO pelanggan VALUES (…..,…..,…..);']),
            ],
            [
                'id_sesi' => 11,
                'tipe' => 'mcq',
                'soal' => 'Apa fungsi utama perintah UPDATE dalam SQL?',
                'opsi' => json_encode(['Mengubah data', 'Menghapus data', 'Menambahkan data', 'Mengedit data']),
                'jawaban' => json_encode(['Mengubah data']),
            ],
            [
                'id_sesi' => 11,
                'tipe' => 'mcq',
                'soal' => 'Apa yang terjadi jika kita menjalankan perintah UPDATE tanpa WHERE?',
                'opsi' => json_encode(['Semua data berpindah tabel', 'Semua tabel berubah', 'Semua data menghilang', 'Semua baris berubah']),
                'jawaban' => json_encode(['Semua baris berubah']),
            ],
            [
                'id_sesi' => 11,
                'tipe' => 'mcq',
                'soal' => 'Perintah mana yang benar untuk mengubah nama siswa dengan ID?',
                'opsi' => json_encode(['UPDATE siswa SET nama = "..." WHERE id...;', 'MODIFY siswa SET nama = "..." WHERE id...;', 'CHANGE siswa SET nama = "..." WHERE id...;']),
                'jawaban' => json_encode(['UPDATE siswa SET nama = "..." WHERE id...;']),
            ],
            [
                'id_sesi' => 11,
                'tipe' => 'multiple',
                'soal' => 'Bagaimana cara mengubah nilai kolom gaji menjadi 14000000 untuk karyawan dengan ID 10?',
                'opsi' => json_encode(['CHANGE', 'UPDATE', 'TRANSFORM', 'WHERE', 'FROM', 'FOR']),
                'jawaban' => json_encode(['UPDATE', 'WHERE']),
            ],
            [
                'id_sesi' => 11,
                'tipe' => 'mcq',
                'soal' => 'Apa yang terjadi jika perintah UPDATE digunakan tanpa menentukan nilai baru?',
                'opsi' => json_encode(['SQL akan menampilkan error', 'Data tidak akan berubah', 'Semua nilai akan menjadi NULL']),
                'jawaban' => json_encode(['SQL akan menampilkan error']),
            ],
            [
                'id_sesi' => 11,
                'tipe' => 'multiple',
                'soal' => 'Cara mengubah status "Proses" menjadi "Selesai"',
                'opsi' => json_encode(['EDIT', 'DROP', 'UPDATE', 'CHOOSE', 'SET', 'FROM', 'WHERE', 'IN']),
                'jawaban' => json_encode(['UPDATE', 'SET', 'WHERE']),
            ],
            [
                'id_sesi' => 11,
                'tipe' => 'mcq',
                'soal' => 'Bagaimana cara untuk mengubah data lebih dari satu kolom?',
                'opsi' => json_encode(['UPDATE...SET.....WHERE', 'UPDATE...SET...AND...WHERE', 'UPDATE...MODIFY...WHERE', 'UPDATE...MODIFY...AND...WHERE']),
                'jawaban' => json_encode(['UPDATE...SET.....WHERE']),
            ],
            [
                'id_sesi' => 11,
                'tipe' => 'multiple',
                'soal' => 'Menambahkan 10% ke gaji semua karyawan tanpa mengubah ID?',
                'opsi' => json_encode(['CHANGE', 'UPDATE', 'CHOOSE', 'WHERE', 'IN', 'SET']),
                'jawaban' => json_encode(['UPDATE', 'SET']),
            ],
            [
                'id_sesi' => 11,
                'tipe' => 'mcq',
                'soal' => 'Perintah apa yang digunakan untuk mengubah data dalam tabel?',
                'opsi' => json_encode(['CHANGE', 'DROP', 'UPDATE', 'EDIT']),
                'jawaban' => json_encode(['UPDATE']),
            ],
            [
                'id_sesi' => 11,
                'tipe' => 'multiple',
                'soal' => 'Apa kegunaan kata kunci SET dalam perintah UPDATE?',
                'opsi' => json_encode(['Baris', 'Kolom', 'Nilai', 'Jumlah', 'Data', 'Perintah']),
                'jawaban' => json_encode(['Baris', 'Nilai']),
            ],
            [
                'id_sesi' => 12,
                'tipe' => 'text',
                'soal' => 'Apa fungsi utama perintah DELETE dalam SQL?',
                'opsi' => null,
                'jawaban' => json_encode(['Menghapus']),
            ],
            [
                'id_sesi' => 12,
                'tipe' => 'multiple',
                'soal' => 'Apa perbedaan utama antara DELETE dan TRUNCATE?',
                'opsi' => json_encode([
                    'DELETE bisa di-rollback',
                    'DELETE mereset auto-increment',
                    'DELETE menghapus struktur tabel',
                    'TRUNCATE lebih cepat',
                    'TRUNCATE menghapus struktur tabel',
                    'TRUNCATE mereset auto-increment'
                ]),
                'jawaban' => json_encode(['DELETE bisa di-rollback', 'TRUNCATE menghapus struktur tabel']),
            ],
            [
                'id_sesi' => 12,
                'tipe' => 'mcq',
                'soal' => 'Pilih pernyataan yang benar tentang DELETE:',
                'opsi' => json_encode([
                    'DELETE dapat menghapus struktur tabel.',
                    'DELETE hanya dapat digunakan dengan satu kondisi.',
                    'DELETE dapat menghapus data tabel',
                    'DELETE tidak bisa digunakan dengan WHERE.'
                ]),
                'jawaban' => json_encode(['DELETE dapat menghapus data tabel']),
            ],
            [
                'id_sesi' => 12,
                'tipe' => 'multiple',
                'soal' => 'Apa yang terjadi jika kita menjalankan perintah DELETE FROM siswa; tanpa WHERE?',
                'opsi' => json_encode(['Terhapus', 'Terpindah', 'Tersalin', 'Tetap ada', 'Ikut terhapus', 'Menghilang']),
                'jawaban' => json_encode(['Terhapus', 'Tetap ada']),
            ],
            [
                'id_sesi' => 12,
                'tipe' => 'mcq',
                'soal' => 'Manakah perintah yang benar untuk menghapus siswa dengan ID 10?',
                'opsi' => json_encode([
                    'DELETE.....WHERE id = 10;',
                    'REMOVE FROM.....WHERE id = 10;',
                    'DELETE FROM.....WHERE id = 10;',
                    'DROP.....WHERE id = 10;'
                ]),
                'jawaban' => json_encode(['DELETE FROM.....WHERE id = 10;']),
            ],
            [
                'id_sesi' => 12,
                'tipe' => 'mcq',
                'soal' => 'Apa perbedaan utama antara DELETE dan DROP?',
                'opsi' => json_encode([
                    'Hanya tabel dan keseluruhan',
                    'Kecepatan menghapus',
                    'Delete bisa di rollback',
                    'Drop menghapus permanen'
                ]),
                'jawaban' => json_encode(['Hanya tabel dan keseluruhan']),
            ],
            [
                'id_sesi' => 12,
                'tipe' => 'text',
                'soal' => 'Bagaimana cara menghapus semua data dalam tabel produk dan mereset auto-increment?',
                'opsi' => null,
                'jawaban' => json_encode(['TRUNCATE']),
            ],
            [
                'id_sesi' => 12,
                'tipe' => 'mcq',
                'soal' => 'Perintah berikut digunakan untuk apa? DELETE FROM pelanggan WHERE nama = "Andi";',
                'opsi' => json_encode([
                    'Menghapus data "Andi"',
                    'Menghapus tabel pelanggan',
                    'Mengubah data "Andi"',
                    'Mencari data "Andi"'
                ]),
                'jawaban' => json_encode(['Menghapus data "Andi"']),
            ],
            [
                'id_sesi' => 12,
                'tipe' => 'mcq',
                'soal' => 'Pilih perintah yang akan menghapus semua siswa dengan nilai kurang dari 140:',
                'opsi' => json_encode([
                    'DELETE FROM siswa WHERE nilai < 140;',
                    'REMOVE siswa WHERE nilai < 140;',
                    'DROP siswa WHERE nilai < 140;',
                    'DELETE nilai FROM siswa WHERE nilai < 140;'
                ]),
                'jawaban' => json_encode(['DELETE FROM siswa WHERE nilai < 140;']),
            ],
            [
                'id_sesi' => 12,
                'tipe' => 'mcq',
                'soal' => 'Apakah benar DELETE bisa digunakan tanpa WHERE?',
                'opsi' => json_encode(['Benar', 'Salah']),
                'jawaban' => json_encode(['Benar']),
            ],
            [
                'id_sesi' => 13,
                'tipe' => 'mcq',
                'soal' => 'Perintah SQL apa yang digunakan untuk menampilkan semua kolom dalam tabel?',
                'opsi' => json_encode(['SHOW FROM nama_tabel;', 'SELECT ALL FROM nama_tabel;', 'SELECT FROM nama_tabel;', 'GET FROM nama_tabel;']),
                'jawaban' => json_encode(['SELECT FROM nama_tabel;']),
            ],
            [
                'id_sesi' => 13,
                'tipe' => 'mcq',
                'soal' => 'Perintah berikut digunakan untuk menampilkan nama dan usia dari tabel siswa:',
                'opsi' => json_encode(['SELECT FROM siswa;', 'SELECT nama, usia FROM siswa;', 'SHOW nama, usia FROM siswa;', 'DISPLAY nama, usia FROM siswa;']),
                'jawaban' => json_encode(['SELECT nama, usia FROM siswa;']),
            ],
            [
                'id_sesi' => 13,
                'tipe' => 'mcq',
                'soal' => 'Perintah SELECT digunakan untuk:',
                'opsi' => json_encode(['Menghapus data dalam tabel', 'Menampilkan data dari tabel', 'Mengubah struktur tabel', 'Menambahkan data ke tabel']),
                'jawaban' => json_encode(['Menampilkan data dari tabel']),
            ],
            [
                'id_sesi' => 13,
                'tipe' => 'mcq',
                'soal' => 'Jika tabel pegawai memiliki kolom id, nama, gaji, bagaimana cara menampilkan hanya kolom nama dan gaji?',
                'opsi' => json_encode(['SELECT id, nama FROM pegawai;', 'SELECT nama, gaji FROM pegawai;', 'SHOW nama, gaji FROM pegawai;', 'GET nama, gaji FROM pegawai;']),
                'jawaban' => json_encode(['SELECT nama, gaji FROM pegawai;']),
            ],
            [
                'id_sesi' => 13,
                'tipe' => 'mcq',
                'soal' => 'Perintah SELECT  FROM produk; akan:',
                'opsi' => json_encode(['Menampilkan semua data dalam tabel produk', 'Menghapus semua data dalam tabel produk', 'Mengubah semua data dalam tabel produk', 'Menampilkan hanya satu baris dari tabel produk']),
                'jawaban' => json_encode(['Menampilkan semua data dalam tabel produk']),
            ],
            [
                'id_sesi' => 13,
                'tipe' => 'text',
                'soal' => 'Apa perintah SQL untuk menampilkan semua data dari tabel karyawan?',
                'opsi' => null,
                'jawaban' => json_encode(['SELECT * FROM karyawan']),
            ],
            [
                'id_sesi' => 13,
                'tipe' => 'text',
                'soal' => 'Jika tabel buku memiliki kolom judul, penulis, tahun, bagaimana cara menampilkan hanya kolom judul?',
                'opsi' => null,
                'jawaban' => json_encode(['SELECT judul FROM buku']),
            ],
            [
                'id_sesi' => 13,
                'tipe' => 'text',
                'soal' => 'Bagaimana cara menampilkan seluruh kolom dalam tabel pelanggan?',
                'opsi' => null,
                'jawaban' => json_encode(['SELECT * FROM pelanggan']),
            ],
            [
                'id_sesi' => 13,
                'tipe' => 'mcq',
                'soal' => 'Perintah SELECT nama, usia FROM siswa; akan menampilkan semua kolom dalam tabel siswa.',
                'opsi' => json_encode(['Benar', 'Salah']),
                'jawaban' => json_encode(['Salah']),
            ],
            [
                'id_sesi' => 13,
                'tipe' => 'mcq',
                'soal' => 'Perintah SELECT  FROM pelanggan; akan menampilkan seluruh data dalam tabel pelanggan.',
                'opsi' => json_encode(['Benar', 'Salah']),
                'jawaban' => json_encode(['Benar']),
            ],
            [
                'id_sesi' => 14,
                'tipe' => 'mcq',
                'soal' => 'Perintah WHERE dalam SQL digunakan untuk:',
                'opsi' => json_encode(['Menampilkan semua data dalam tabel', 'Memfilter data berdasarkan kondisi tertentu', 'Menghapus data dari tabel', 'Mengubah struktur tabel']),
                'jawaban' => json_encode(['Memfilter data berdasarkan kondisi tertentu']),
            ],
            [
                'id_sesi' => 14,
                'tipe' => 'mcq',
                'soal' => 'Bagaimana cara menampilkan semua data yang berusia lebih dari 17 tahun?',
                'opsi' => json_encode(['SELECT FROM…..WHERE usia >= 17;', 'SELECT FROM…..WHERE usia < 17;', 'SELECT FROM…..WHERE usia > 17;', 'SELECT FROM…..WHERE usia != 17;']),
                'jawaban' => json_encode(['SELECT FROM…..WHERE usia > 17;']),
            ],
            [
                'id_sesi' => 14,
                'tipe' => 'mcq',
                'soal' => 'Manakah perintah yang benar untuk menampilkan siswa dengan nama "Budi"?',
                'opsi' => json_encode(['SELECT FROM…..WHERE nama = "Budi";', 'SELECT FROM…..WHERE nama LIKE "Budi";', 'SELECT FROM…..WHERE nama == "Budi";', 'SELECT FROM…..WHERE nama IN "Budi";']),
                'jawaban' => json_encode(['SELECT FROM…..WHERE nama = "Budi";']),
            ],
            [
                'id_sesi' => 14,
                'tipe' => 'mcq',
                'soal' => 'Perintah LIKE "B%" akan menampilkan:',
                'opsi' => json_encode(['Semua nama yang diawali dengan huruf B', 'Semua nama yang mengandung huruf B', 'Semua nama yang berakhiran huruf B', 'Semua nama yang hanya terdiri dari huruf B']),
                'jawaban' => json_encode(['Semua nama yang diawali dengan huruf B']),
            ],
            [
                'id_sesi' => 14,
                'tipe' => 'mcq',
                'soal' => 'Perintah SELECT FROM produk WHERE harga BETWEEN 10000 AND 140000; akan menampilkan:',
                'opsi' => json_encode(['Produk dengan harga lebih dari 140000', 'Produk dengan harga kurang dari 10000', 'Produk dengan harga antara 10000 dan 140000', 'Produk dengan harga lebih dari 10000 dan kurang dari 140000']),
                'jawaban' => json_encode(['Produk dengan harga antara 10000 dan 140000']),
            ],
            [
                'id_sesi' => 14,
                'tipe' => 'mcq',
                'soal' => 'Perintah SQL untuk menampilkan siswa yang tidak berusia 17 tahun adalah?',
                'opsi' => json_encode(['SELECT FROM siswa WHERE usia != 17;', 'SELECT FROM siswa WHERE usia < 17;', 'SELECT FROM siswa WHERE usia LIKE 17;', 'SELECT FROM siswa WHERE usia BETWEEN 17;']),
                'jawaban' => json_encode(['SELECT FROM siswa WHERE usia != 17;']),
            ],
            [
                'id_sesi' => 14,
                'tipe' => 'mcq',
                'soal' => 'Bagaimana cara menampilkan siswa yang namanya mengandung huruf "A"?',
                'opsi' => json_encode(['SELECT FROM siswa WHERE nama LIKE "A";', 'SELECT FROM siswa WHERE nama LIKE "%A%";', 'SELECT FROM siswa WHERE nama = "A";', 'SELECT FROM siswa WHERE nama = "%A%";']),
                'jawaban' => json_encode(['SELECT FROM siswa WHERE nama LIKE "%A%";']),
            ],
            [
                'id_sesi' => 14,
                'tipe' => 'mcq',
                'soal' => 'Bagaimana cara menampilkan jabatan “Manager” dan “Supervisor” dari tabel pegawai?',
                'opsi' => json_encode(['SELECT * FROM pegawai WHERE jabatan IN (“Manager”, “Supervisor”);', 'SELECT FROM pegawai WHERE jabatan = “Manager” OR jabatan = “Supervisor”;', 'SELECT * FROM pegawai WHERE jabatan LIKE “Manager”, “Supervisor”;', 'SELECT FROM pegawai WHERE jabatan LIKE “%Manager%”, “%Supervisor%”;']),
                'jawaban' => json_encode(['SELECT * FROM pegawai WHERE jabatan IN (“Manager”, “Supervisor”);']),
            ],
            [
                'id_sesi' => 14,
                'tipe' => 'mcq',
                'soal' => 'Perintah SELECT FROM siswa WHERE usia <= 17; akan menampilkan siswa yang berusia 17 tahun atau kurang.',
                'opsi' => json_encode(['Benar', 'Salah']),
                'jawaban' => json_encode(['Benar']),
            ],
            [
                'id_sesi' => 14,
                'tipe' => 'mcq',
                'soal' => 'Perintah SELECT FROM siswa WHERE nama LIKE “%A”; akan menampilkan semua siswa yang namanya diawali huruf "A".',
                'opsi' => json_encode(['Benar', 'Salah']),
                'jawaban' => json_encode(['Salah']),
            ],
            [
                'id_sesi' => 15,
                'tipe' => 'mcq',
                'soal' => 'Apa fungsi dari klausa ORDER BY dalam SQL?',
                'opsi' => json_encode(['Menghapus data dalam tabel', 'Mengurutkan data dalam tabel', 'Menambahkan data ke tabel', 'Memfilter data dalam tabel']),
                'jawaban' => json_encode(['Mengurutkan data dalam tabel']),
            ],
            [
                'id_sesi' => 15,
                'tipe' => 'mcq',
                'soal' => 'Perintah untuk mengurutkan berdasarkan nama dari AZ adalah:',
                'opsi' => json_encode(['SELECT FROM…..ORDER BY nama DESC;', 'SELECT FROM…..ORDER BY nama ASC;', 'SELECT FROM…..SORT BY nama;', 'SELECT FROM…..GROUP BY nama;']),
                'jawaban' => json_encode(['SELECT FROM…..ORDER BY nama ASC;']),
            ],
            [
                'id_sesi' => 15,
                'tipe' => 'mcq',
                'soal' => 'Bagaimana cara mengurutkan data pegawai berdasarkan gaji dari yang tertinggi ke terendah?',
                'opsi' => json_encode(['SELECT FROM pegawai ORDER BY gaji ASC;', 'SELECT FROM pegawai ORDER BY gaji DESC;', 'SELECT FROM pegawai SORT BY gaji;', 'SELECT FROM pegawai FILTER BY gaji DESC;']),
                'jawaban' => json_encode(['SELECT FROM pegawai ORDER BY gaji DESC;']),
            ],
            [
                'id_sesi' => 15,
                'tipe' => 'mcq',
                'soal' => 'Jika kita tidak menentukan ASC atau DESC dalam ORDER BY, maka urutan defaultnya adalah:',
                'opsi' => json_encode(['DESC', 'ASC', 'Tidak ada urutan', 'Acak']),
                'jawaban' => json_encode(['ASC']),
            ],
            [
                'id_sesi' => 15,
                'tipe' => 'mcq',
                'soal' => 'Apa yang terjadi jika menggunakan ORDER BY pada kolom yang berisi angka?',
                'opsi' => json_encode(['Data akan diurutkan berdasarkan abjad', 'Data akan diurutkan dari nilai terkecil ke terbesar (default)', 'Data akan dihapus secara otomatis', 'Data tidak bisa diurutkan']),
                'jawaban' => json_encode(['Data akan diurutkan dari nilai terkecil ke terbesar (default)']),
            ],
            [
                'id_sesi' => 15,
                'tipe' => 'text',
                'soal' => 'Perintah SQL untuk mengurutkan data pelanggan berdasarkan nama dari Z ke A adalah?',
                'opsi' => null,
                'jawaban' => json_encode(['DESC']),
            ],
            [
                'id_sesi' => 15,
                'tipe' => 'text',
                'soal' => 'Bagaimana cara menampilkan daftar produk berdasarkan harga dari yang termurah ke yang termahal?',
                'opsi' => null,
                'jawaban' => json_encode(['ASC']),
            ],
            [
                'id_sesi' => 15,
                'tipe' => 'text',
                'soal' => 'Jika ingin mengurutkan pegawai berdasarkan usia tertua ke termuda, perintahnya adalah?',
                'opsi' => null,
                'jawaban' => json_encode(['DESC']),
            ],
            [
                'id_sesi' => 15,
                'tipe' => 'mcq',
                'soal' => 'Perintah SELECT FROM siswa ORDER BY nama; akan mengurutkan nama siswa secara menurun (Z ke A).',
                'opsi' => json_encode(['Benar', 'Salah']),
                'jawaban' => json_encode(['Salah']),
            ],
            [
                'id_sesi' => 15,
                'tipe' => 'mcq',
                'soal' => 'ORDER BY bisa digunakan untuk mengurutkan data berdasarkan lebih dari satu kolom.',
                'opsi' => json_encode(['Benar', 'Salah']),
                'jawaban' => json_encode(['Benar']),
            ],
            [
                'id_sesi' => 16,
                'tipe' => 'mcq',
                'soal' => 'Apa fungsi utama dari LIMIT dalam SQL?',
                'opsi' => json_encode(['Menghapus data dalam tabel', 'Membatasi jumlah data yang ditampilkan', 'Mengurutkan data secara otomatis', 'Menggabungkan dua tabel']),
                'jawaban' => json_encode(['Membatasi jumlah data yang ditampilkan']),
            ],
            [
                'id_sesi' => 16,
                'tipe' => 'mcq',
                'soal' => 'Perintah untuk menampilkan hanya 10 baris pertama dari tabel pelanggan adalah:',
                'opsi' => json_encode(['SELECT FROM pelanggan ORDER 10;', 'SELECT FROM pelanggan LIMIT 10;', 'SELECT FROM pelanggan WHERE LIMIT 10;', 'SELECT FROM pelanggan TOP 10;']),
                'jawaban' => json_encode(['SELECT FROM pelanggan LIMIT 10;']),
            ],
            [
                'id_sesi' => 16,
                'tipe' => 'mcq',
                'soal' => 'Bagaimana cara menampilkan 5 produk termahal dari tabel produk?',
                'opsi' => json_encode(['SELECT FROM produk ORDER BY harga ASC LIMIT 5;', 'SELECT FROM produk ORDER BY harga DESC LIMIT 5;', 'SELECT FROM produk WHERE harga DESC LIMIT 5;', 'SELECT FROM produk SORT BY harga DESC LIMIT 5;']),
                'jawaban' => json_encode(['SELECT FROM produk ORDER BY harga DESC LIMIT 5;']),
            ],
            [
                'id_sesi' => 16,
                'tipe' => 'mcq',
                'soal' => 'Jika tabel pegawai memiliki 100 data, tetapi kita hanya ingin melihat 7 data pertama, perintah yang benar adalah:',
                'opsi' => json_encode(['SELECT FROM pegawai LIMIT 7;', 'SELECT FROM pegawai ORDER BY 7;', 'SELECT FROM pegawai WHERE LIMIT 7;', 'SELECT TOP 7 FROM pegawai;']),
                'jawaban' => json_encode(['SELECT FROM pegawai LIMIT 7;']),
            ],
            [
                'id_sesi' => 16,
                'tipe' => 'mcq',
                'soal' => 'Perintah LIMIT digunakan untuk:',
                'opsi' => json_encode(['Menghapus data tertentu dari tabel', 'Menentukan jumlah kolom yang ditampilkan', 'Mengatur jumlah baris yang ditampilkan', 'Mengurutkan data dalam tabel']),
                'jawaban' => json_encode(['Mengatur jumlah baris yang ditampilkan']),
            ],
            [
                'id_sesi' => 16,
                'tipe' => 'text',
                'soal' => 'Bagaimana cara menampilkan 3 siswa tertua dari tabel siswa?',
                'opsi' => null,
                'jawaban' => json_encode(['SELECT FROM siswa ORDER BY usia DESC LIMIT 3;']),
            ],
            [
                'id_sesi' => 16,
                'tipe' => 'text',
                'soal' => 'Jika ingin menampilkan hanya 1 data pertama dari tabel pelanggan, perintahnya adalah?',
                'opsi' => null,
                'jawaban' => json_encode(['SELECT FROM pelanggan LIMIT 1;']),
            ],
            [
                'id_sesi' => 16,
                'tipe' => 'text',
                'soal' => 'Bagaimana cara menampilkan 10 data pertama dari tabel karyawan yang diurutkan berdasarkan nama secara alfabetis?',
                'opsi' => null,
                'jawaban' => json_encode(['SELECT FROM karyawan ORDER BY nama ASC LIMIT 10;']),
            ],
            [
                'id_sesi' => 16,
                'tipe' => 'mcq',
                'soal' => 'Perintah SELECT FROM siswa ORDER BY nama DESC LIMIT 5; akan menampilkan 5 siswa pertama berdasarkan nama dari AZ.',
                'opsi' => json_encode(['Benar', 'Salah']),
                'jawaban' => json_encode(['Salah']),
            ],
            [
                'id_sesi' => 16,
                'tipe' => 'mcq',
                'soal' => 'LIMIT dapat digunakan tanpa ORDER BY dalam SQL.',
                'opsi' => json_encode(['Benar', 'Salah']),
                'jawaban' => json_encode(['Benar']),
            ],
        ]);
    }
}
